#!/bin/bash
# =============================================================
#  Setup "Theme Sw1tcher"
# =============================================================
set -e
source "./utils.sh"

dir_dot_conf="$HOME/.config"
dir_hypr=$HOME/.config/hypr
dir_hypr_conf="$dir_hypr/hyprland.lua"
dir_hypr_colors="$dir_hypr/config/"
dir_user_wallpaper="$HOME/Pictures/Wallpapers"
dir_wal_templates="$HOME/.config/wal"
dir_kvantum_pywal="$HOME/.config/Kvantum/pywal"
dir_qt="$HOME/.config/qt6ct"
dir_qt6ct_colors="$dir_qt/colors"
qt6ct_conf="$dir_qt/qt6ct.conf"
kitty_conf="$HOME/.config/kitty/kitty.conf"

echo "$dir_dot_conf"


log_step "Creation of folders..."
mkdir -p "$dir_user_wallpaper"
mkdir -p "$dir_wal_templates"
mkdir -p "$dir_kvantum_pywal"
mkdir -p "$dir_qt6ct_colors"
mkdir -p "$dir_dot_conf"

# -------------------------------------------------------------
# Install Dependencies
# -------------------------------------------------------------
# Pacman packages
log_step "Installing core and basic packages via Pacman..."
sudo pacman -S --needed --noconfirm \
    yay \
    ttf-jetbrains-mono-nerd \
    qt5ct qt6ct rofi \

# Yay packages
log_step "Installing AUR packages..."
yay -S --needed --noconfirm \
    awww python-pywal16 wpgtk nwg-look papirus-icon-theme kvantum \

# -------------------------------------------------------------
# Template Kvantum SVG for pywal
# -------------------------------------------------------------
log_step "Installing Templates for QT, GTK, Pywal, and Hyprland"
cp -r ./scripts/template/wal $dir_wal_templates

# -------------------------------------------------------------
# Symlink qt6ct/Kvantum colors → cache wal
# -------------------------------------------------------------
log_step "Symlink qt6ct colors..."
ln -sf "$HOME/.cache/wal/colors-qt6ct.conf" "$dir_qt6ct_colors/pywal.conf"
log_step "Symlink Kvantum colors..."
ln -sf "$HOME/.cache/wal/pywal.svg" "$dir_kvantum_pywal/pywal.svg"
ln -sf "$HOME/.cache/wal/pywal.kvconfig" "$dir_kvantum_pywal/pywal.kvconfig"

# -------------------------------------------------------------
# Config qt6ct
# -------------------------------------------------------------
log_step "Configuration qt6ct..."
if [ -f "$qt6ct_conf" ]; then
    sed -i 's|color_scheme_path=.*|color_scheme_path=/home/'"$USER"'/.config/qt6ct/colors/pywal.conf|' "$qt6ct_conf"
    sed -i 's/custom_palette=false/custom_palette=true/' "$qt6ct_conf"
    log_success "Options have been added to $qt6ct_conf file."
else
    mkdir -p "$(dirname "$qt6ct_conf")"
    cp ./scripts/template/qt/qt.conf $qt6ct_conf
    log_success "A new $qt6ct_conf file has been created."
fi

# -------------------------------------------------------------
# Env Variables Qt in hyprland
# -------------------------------------------------------------
log_step "Checking the Qt environment variables in Hyprland..."
if [ "$dir_hypr_conf" ]; then
    if ! grep -q "QT_QPA_PLATFORMTHEME" "$dir_hypr_conf"; then
        echo "-- Qt theming" >> "$dir_hypr_conf"
        echo "hl.env(\"QT_QPA_PLATFORMTHEME\", \"qt6ct\")" >> "$dir_hypr_conf"
        log_success "Options have been added  to hyprland.conf"
    else
        log_info "Already present in hyprland.lua"
    fi
else
    log_warn "hyprland.lua not found, add manually: ${BOLD}hl.env(\"QT_QPA_PLATFORMTHEME\", \"qt6ct\")${NC}"
fi

# -------------------------------------------------------------
# Install "theme-sw1tcher.sh"
# -------------------------------------------------------------
log_step "Install theme-sw1tch.sh script..."
cp -r "./scripts/template/theme-sw1tcher" $dir_dot_conf

# -------------------------------------------------------------
# Kitty Theme
# -------------------------------------------------------------
log_step "Colors in Kitty terminal"
if ask_yes_no "Do you want to configure colors in Kitty?"; then
    if ! grep -q "colors-kitty.conf" "$kitty_conf"; then
        echo -e "\n# Include the colors generated by Pywal\ninclude ~/.cache/wal/colors-kitty.conf" >> "$kitty_conf"
        log_success "Kitty configured successfully."
    else
        log_info "Kitty already configured."
    fi
else
    log_info "Skipping colors in Kitty configuration."
fi

# -------------------------------------------------------------
# Hyprland window Theme
# -------------------------------------------------------------
log_step "Colors in Hyprland window"
if ask_yes_no "Do you want to configure colors in Hyprland window?"; then
    cp ./scripts/template/hypr/colors.lua $dir_hypr_colors
else
    log_info "Skipping colors in Hyprland configuration."
fi

echo ""
echo "🎉 Pywal Setup complete!"
echo ""
echo "Remaining manual checklist:"
echo " 1. Copy your wallpapers to $dir_user_wallpaper"
echo " 2. Run "$dir_dot_conf/theme-sw1tcher/theme-sw1tcher.sh" to test"
echo -e " 3. Add a keyboard shortcut to switch themes --> ${BLUE}${BOLD}\"hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd("sh ~/.config/hypr/scripts/theme-sw1tch.sh"))\"${NC}"
echo ""